version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: finance-n8n
    env_file:
      - .env
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://unnibbed-unthrilled-averi.ngrok-free.dev
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_PAYLOAD_SIZE_MAX=10
    ports:
      - '${N8N_PORT}:5678'
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - finance-network

  mongodb:
    image: mongo:7
    container_name: finance-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: analytics_db
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - finance-network

  redis:
    image: redis:7-alpine
    container_name: finance-redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    networks:
      - finance-network
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: finance-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT}:15672' #UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - finance-network
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: backend/auth_service/Dockerfile
      target: development
    container_name: finance-auth-service
    env_file:
      - .env
    volumes:
      - ./backend/auth_service:/app/backend/auth_service
      - ./backend/shared/dotnet-shared:/app/backend/shared/dotnet-shared
      - /app/backend/auth_service/src/AuthService.API/bin
      - /app/backend/auth_service/src/AuthService.API/obj
      - /app/backend/auth_service/src/AuthService.Application/bin
      - /app/backend/auth_service/src/AuthService.Application/obj
    ports:
      - '${AUTH_SERVICE_PORT}:3006'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3006
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - finance-network

  user-service:
    build:
      context: .
      dockerfile: backend/user_service/Dockerfile
    container_name: finance-user-service
    env_file:
      - .env
    ports:
      - '${USER_SERVICE_PORT}:3001'
      - '${GRPC_USER_SERVICE_PORT}:50054'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq
    networks:
      - finance-network
    volumes:
      - ./backend/user_service:/app/backend/user_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - /app/backend/user_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  account-service:
    build:
      context: .
      dockerfile: backend/account_service/Dockerfile
    container_name: finance-account-service
    env_file:
      - .env
    ports:
      - '${ACCOUNT_SERVICE_PORT}:3002'
      - '${GRPC_ACCOUNT_SERVICE_PORT}:50051'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq
    networks:
      - finance-network
    volumes:
      - ./backend/account_service:/app/backend/account_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - ./backend/shared/protos:/app/backend/shared/protos
      - /app/backend/account_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  transaction-service:
    build:
      context: .
      dockerfile: backend/transaction_service/Dockerfile
      target: development
    container_name: finance-transaction-service
    env_file:
      - .env
    volumes:
      - ./backend/transaction_service:/app/backend/transaction_service
      - ./backend/shared/dotnet-shared:/app/backend/shared/dotnet-shared
      - ./backend/shared/protos:/app/backend/shared/protos
      - /app/backend/transaction_service/src/TransactionService.API/bin
      - /app/backend/transaction_service/src/TransactionService.API/obj
      - /app/backend/transaction_service/src/TransactionService.Application/bin
      - /app/backend/transaction_service/src/TransactionService.Application/obj
    ports:
      - '${TRANSACTION_SERVICE_PORT}:3007'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3007
    depends_on:
      - redis
      - rabbitmq
    networks:
      - finance-network

  category-service:
    build:
      context: .
      dockerfile: backend/category_service/Dockerfile
    container_name: finance-category-service
    env_file:
      - .env
    ports:
      - '${CATEGORY_SERVICE_PORT}:3003'
      - '${GRPC_CATEGORY_SERVICE_PORT}:50052'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq
    networks:
      - finance-network
    volumes:
      - ./backend/category_service:/app/backend/category_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - ./backend/shared/protos:/app/backend/shared/protos
      - /app/backend/category_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  analytics-service:
    build:
      context: .
      dockerfile: backend/analytics_service/Dockerfile
    container_name: finance-analytics-service
    env_file:
      - .env
    ports:
      - '${ANALYTICS_SERVICE_PORT}:3004'
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - finance-network
    volumes:
      - ./backend/analytics_service:/app/backend/analytics_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - ./backend/shared/protos:/app/backend/shared/protos
      - /app/backend/analytics_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  notification-service:
    build:
      context: .
      dockerfile: backend/notification_service/Dockerfile
    container_name: finance-notification-service
    env_file:
      - .env
    ports:
      - '${NOTIFICATION_SERVICE_PORT}:3005'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq
    networks:
      - finance-network
    volumes:
      - ./backend/notification_service:/app/backend/notification_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - /app/backend/notification_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  budget-service:
    build:
      context: .
      dockerfile: backend/budget_service/Dockerfile
    container_name: finance-budget-service
    env_file:
      - .env
    ports:
      - '${BUDGET_SERVICE_PORT}:3008'
      - '${GRPC_BUDGET_SERVICE_PORT}:50053'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - rabbitmq
    networks:
      - finance-network
    volumes:
      - ./backend/budget_service:/app/backend/budget_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - ./backend/shared/protos:/app/backend/shared/protos
      - /app/backend/budget_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  ai-service:
    build:
      context: .
      dockerfile: backend/ai_service/Dockerfile
    container_name: finance-ai-service
    env_file: .env
    ports:
      - '${AI_PORT}:4005'
    environment:
      - NODE_ENV=development
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - finance-network
    volumes:
      - ./backend/ai_service:/app/backend/ai_service
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - /app/backend/ai_service/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  gateway:
    build:
      context: .
      dockerfile: backend/gateway/Dockerfile
    container_name: finance-gateway
    env_file:
      - .env
    ports:
      - '${GATEWAY_PORT}:3000'
    depends_on:
      - auth-service
      - user-service
      - account-service
      - transaction-service
      - category-service
      - analytics-service
      - notification-service
      - budget-service
    networks:
      - finance-network
    volumes:
      - ./backend/gateway:/app/backend/gateway
      - ./backend/shared/rabbitmq-client:/app/backend/shared/rabbitmq-client
      - /app/backend/gateway/node_modules
      - /app/backend/shared/rabbitmq-client/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
  rabbitmq-data:
  n8n-data:
