envVarGroups:
  - name: common-secrets
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: D8F9G0H1J2K3L4M5N6B7V8C9X0Z1Q2W3E4R5T6Y7U8I9O0P1A2S3D4F5G6H7J8K9L0M1N2B3V4C5X6Z7Q8W9E0R1T2Y3U4I5O6P7A8S9D0F1G2H3J4K5L6M7N8B9V0C1X2Z3Q4W5E6R7T8Y9U0I1O2P3A4S5D6F7G8H9J0K1L2M3N4B5V6C7X8Z9Q0W1E2R3T4Y5U6I7O8P9A0S1D2F3G4H5J6K7L8Z9X0C1V2B3N4M5Q6W7
      - key: REFRESH_TOKEN_SECRET
        value: klkasfaxcsafsafnsanc245asf123
      # Dùng chung cho các service Node.js
      - key: RABBITMQ_URL
        sync: false
      # Dùng chung cho các service .NET (Dán cùng URL Rabbit vào đây khi Render hỏi)
      - key: ConnectionStrings__RabbitMQConnection
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_PASSWORD
        value: '16072004'

services:
  # 1. GATEWAY
  - type: web
    name: gateway
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/gateway/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3000
      - key: USER_SERVICE_URL
        value: http://user-service:3001
      - key: ACCOUNT_SERVICE_URL
        value: http://account-service:3002
      - key: CATEGORY_SERVICE_URL
        value: http://category-service:3003
      - key: ANALYTICS_SERVICE_URL
        value: http://analytics-service:3004
      - key: NOTIFICATION_SERVICE_URL
        value: http://notification-service:3005
      - key: AUTH_SERVICE_URL
        value: http://auth-service:3006
      - key: TRANSACTION_SERVICE_URL
        value: http://transaction-service:3007
      - key: BUDGET_SERVICE_URL
        value: http://budget-service:3008
      - key: AI_SERVICE_URL
        value: http://ai-service:4005

  # 2. USER SERVICE
  - type: web
    name: user-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/user_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://postgres:datletan16072004@db.mdzmjrxpntwapuiyhqdo.supabase.co:5432/postgres?schema=user_service

  # 3. ACCOUNT SERVICE
  - type: web
    name: account-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/account_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        value: postgresql://postgres:datletan16072004@db.mdzmjrxpntwapuiyhqdo.supabase.co:5432/postgres?schema=account_service

  # 4. CATEGORY SERVICE
  - type: web
    name: category-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/category_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        value: postgresql://postgres:datletan16072004@db.mdzmjrxpntwapuiyhqdo.supabase.co:5432/postgres?schema=category_service

  # 5. ANALYTICS SERVICE
  - type: web
    name: analytics-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/analytics_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3004
      - key: MONGODB_URL
        sync: false

  # 6. NOTIFICATION SERVICE
  - type: web
    name: notification-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/notification_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3005

  # 7. AUTH SERVICE (.NET 8)
  - type: web
    name: auth-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/auth_service/Dockerfile.render # TRỎ VÀO FILE MỚI
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3006
      - key: ConnectionStrings__DefaultConnection
        value: Host=aws-1-ap-southeast-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.mdzmjrxpntwapuiyhqdo;Password=datletan16072004;SearchPath=auth_service;Trust Server Certificate=true

  # 8. TRANSACTION SERVICE
  - type: web
    name: transaction-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/transaction_service/Dockerfile.render # TRỎ VÀO FILE MỚI
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3007
      - key: ConnectionStrings__DefaultConnection
        value: Host=aws-1-ap-southeast-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.mdzmjrxpntwapuiyhqdo;Password=datletan16072004;SearchPath=transaction_service;Trust Server Certificate=true
        
  # 9. BUDGET SERVICE
  - type: web
    name: budget-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/budget_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 3008
      - key: DATABASE_URL
        value: postgresql://postgres:datletan16072004@db.mdzmjrxpntwapuiyhqdo.supabase.co:5432/postgres?schema=account_service

  # 10. AI SERVICE
  - type: web
    name: ai-service
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/ai_service/Dockerfile
    plan: free
    envVars:
      - fromGroup: common-secrets
      - key: PORT
        value: 4005
      - key: GEMINI_API_KEY
        value: AIzaSyB70wYdWt5jp57ltXuD9HflCs0EbDRYoCk
      - key: PUBLIC_VAPID_KEY
        value: BLbswT5YhhDfRMT54tR3s5yuZeezIBPkfPLT41MTzmw2Cl3H87V0oY2Fbm71qFJnraMn5A6-QkQ2X9erwdS0LZQ
      - key: PRIVATE_VAPID_KEY
        value: ABpKOu8cq2KflyhdWeDKIq05Uu5m04mdI5qbe--vbmE
